website/accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

website/calendarapp/urls.py
from django.urls import path

from . import views
from .views.other_views import member_join,delete_event

app_name = "calendarapp"


urlpatterns = [
    path("calender/", views.CalendarViewNew.as_view(), name="calendar"),
    path("", views.CalendarView.as_view(), name="calendars"),
    path("event/new/", views.create_event, name="event_new"),
    path("event/delete/", delete_event, name="delete_event"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path("add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"),
    path("event/<int:pk>/remove",views.EventMemberDeleteView.as_view(),name="remove_event",),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path("running-event-list/",views.RunningEventsListView.as_view(),name="running_events",),
    path("upcoming-event-list/",views.UpcomingEventsListView.as_view(),name="upcoming_events",),
    path("member_join/<int:event_id>", member_join, name="member_join"),
]

website/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from .views import DashboardView,error_404_view

urlpatterns = [
    path("admin/", DashboardView.as_view(), name="dashboard"),
    path('database/', admin.site.urls),
    # path('', include('onlinecourse.urls')),
    path('', include('calendarapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('404/', error_404_view, name='404'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    if superuser
    {% if request.user.is_superuser %}
    
    
    <head>
        <meta name="description" content="Event Dashboard" />
        <!-- Twitter meta-->
       
        <meta property="og:description" content="Event Dashboard" />
        <title>{% block title %}{% endblock title  %}</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Main CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        <script src="https://kit.fontawesome.com/2d8174d887.js" crossorigin="anonymous"></script>
        {% block extracss %}
        {% endblock extracss %}
    </head>
    <body class="app sidebar-mini">
        <!-- Navbar-->
        <header class="app-header">
            <a class="app-header__logo" href="#">الدورات</a>
            <!-- Sidebar toggle button-->
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <!-- Navbar Right Menu-->
            <ul class="app-nav">
                <li class="app-search">
                    {% comment %} <input class="app-search__input" type="search" placeholder="Search" /> {% endcomment %}
                    {% comment %} <button class="app-search__button"><i class="fa fa-search"></i></button> {% endcomment %}
                </li>
                <!--Notification Menu-->
               <!-- <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Show notifications"><i class="fa fa-bell-o fa-lg"></i></a>
                    <ul class="app-notification dropdown-menu dropdown-menu-right">
                        <li class="app-notification__title">You have 4 new notifications.</li>
                        <div class="app-notification__content">
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message">Lisa sent you a mail</p>
                                        <p class="app-notification__meta">2 min ago</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message">Mail server not working</p>
                                        <p class="app-notification__meta">5 min ago</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <p class="app-notification__message">Transaction complete</p>
                                        <p class="app-notification__meta">2 days ago</p>
                                    </div>
                                </a>
                            </li>
                            <div class="app-notification__content">
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message">Lisa sent you a mail</p>
                                            <p class="app-notification__meta">2 min ago</p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message">Mail server not working</p>
                                            <p class="app-notification__meta">5 min ago</p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <p class="app-notification__message">Transaction complete</p>
                                            <p class="app-notification__meta">2 days ago</p>
                                        </div>
                                    </a>
                                </li>
                            </div>
                        </div>
                        {% comment %} <li class="app-notification__footer"><a href="#">See all notifications.</a></li> {% endcomment %}
                    </ul>
                </li>
                
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="#"><i class="fa fa-cog fa-lg"></i> Settings</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#"><i class="fa fa-user fa-lg"></i> Profile</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:signout' %}"><i class="fa fa-sign-out fa-lg"></i> Sign Out</a>
                        </li>
                    </ul>
                </li>-->
            </ul>
        </header>
        <!-- Sidebar menu-->
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            <div class="app-sidebar__user">
                <img class="app-sidebar__user-avatar" src="https://fin.aboelezz.com/static/assets/img/logo.png" alt="User Image" height="50px" width="50px"/>
                <div>
                    <p class="app-sidebar__user-name">المركز المالي والأداري</p>
                    <p class="app-sidebar__user-designation">ملتقي </p>
                </div>
            </div>
            <ul class="app-menu">
                {% comment %} <li class="treeview">
                    <a class="app-menu__item" href="{% url 'onlinecourse:courses_dashboard' %}" data-toggle="treeview"><i class="app-menu__icon fa-solid fa-laptop-code"></i><span class="app-menu__label">Courses</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a class="treeview-item" href="{% url 'onlinecourse:courses_dashboard' %}"><i class="icon fa fa-circle-o"></i> All Courses</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'onlinecourse:done_courses' %}"><i class="icon fa fa-circle-o"></i> Done Courses</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'onlinecourse:upcoming_courses' %}"><i class="icon fa fa-circle-o"></i> Upcoming Courses</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'onlinecourse:add_course' %}"><i class="icon fa fa-circle-o"></i> Add new course</a>
                        </li>
                    </ul>
                </li> {% endcomment %}
                <li>
                    <a class="app-menu__item" href="{% url 'dashboard' %}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Dashboard</span></a>
                </li>
                
                <li>
                    <a class="app-menu__item" href="{% url 'calendarapp:calendar' %}"><i class="app-menu__icon fa fa-calendar"></i><span class="app-menu__label">Calendar</span></a>
                </li>
                <li class="treeview">
                    <a class="app-menu__item" href="{% url 'calendarapp:all_events' %}" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">courses</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a class="treeview-item" href="{% url 'calendarapp:running_events' %}"><i class="icon fa fa-circle-o"></i> Running</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'calendarapp:upcoming_events' %}"><i class="icon fa fa-circle-o"></i> Upcoming</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'calendarapp:all_events' %}"><i class="icon fa fa-circle-o"></i> All</a>
                        </li>
                    </ul>
                </li>
                


            </ul>
        </aside>
        <main class="app-content">
            <div class="app-title">
                {% block breadcrumb %}
                {% endblock breadcrumb %}
            </div>
            {% block content %}
            {% endblock content %}
        </main>
        <!-- Essential javascripts for application to work-->
        {% include 'base/js.html' %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.32/dist/sweetalert2.all.min.js"></script>
        
        {% block extrascripts %}
        {% endblock extrascripts %}
    </body>
</html>
{% else %}
    {% include '404.html' %}
    {% endif %}

website/templates/base/js.html
{% load static %}
<script src="{% static 'js/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js'%}"></script>