website/accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

website/calendarapp/urls.py
from django.urls import path

from . import views
from .views.other_views import member_join,delete_event

app_name = "calendarapp"


urlpatterns = [
    path("calender/", views.CalendarViewNew.as_view(), name="calendar"),
    path("", views.CalendarView.as_view(), name="calendars"),
    path("event/new/", views.create_event, name="event_new"),
    path("event/delete/", delete_event, name="delete_event"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path("add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"),
    path("event/<int:pk>/remove",views.EventMemberDeleteView.as_view(),name="remove_event",),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path("running-event-list/",views.RunningEventsListView.as_view(),name="running_events",),
    path("upcoming-event-list/",views.UpcomingEventsListView.as_view(),name="upcoming_events",),
    path("member_join/<int:event_id>", member_join, name="member_join"),
]

website/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from .views import DashboardView,error_404_view

urlpatterns = [
    path("admin/", DashboardView.as_view(), name="dashboard"),
    path('database/', admin.site.urls),
    # path('', include('onlinecourse.urls')),
    path('', include('calendarapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('404/', error_404_view, name='404'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/calendarapp/models/event.py
from datetime import datetime
from django.db import models
from django.urls import reverse

from calendarapp.models import EventAbstract
from accounts.models import User


class EventManager(models.Manager):
    """ Event manager """

    def get_all_events(self, user):
        events = Event.objects.filter(user=user, is_active=True, is_deleted=False)
        return events

    def get_running_events(self, user):
        running_events = Event.objects.filter(
            user=user,
            is_active=True,
            is_deleted=False,
            end_time__gte=datetime.now().date(),
        ).order_by("start_time")
        return running_events
    
    def get_upcoming_events(self, user):
        upcoming_events = Event.objects.filter(
            user=user,
            is_active=False,
            is_deleted=False,
            # start time is greater than or equal to today
            start_time__gte=datetime.now().date(),
        ).order_by("start_time")
        return upcoming_events


class Event(EventAbstract):
    """ Event model """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="events")
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("calendarapp:event-detail", args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse("calendarapp:event-detail", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

website/templates/add_member.html
{% extends 'base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}">الأضافة من صفحة الادمن </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> أضافة</button></td></tr>
  </table>
</form>
{% endblock %}

website/templates/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en" >

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->

  
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/main1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>الملتقى المهني العاشر بجامعة الملك عبدالعزيز</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

        <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <!-- Animation -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <!-- magnific -->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <!-- carousel -->
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <!-- isotop -->
    <link rel="stylesheet" href="{% static 'assets/css/isotop.css' %}">
    <!-- ico fonts -->
    <link rel="stylesheet" href="{% static 'assets/css/xsIcon.css' %}">
    <!-- Template styles-->
    <link rel="stylesheet" href="{% static 'assets/css/style-v3.css' %}">
    <!-- Responsive styles-->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    {% comment %} <link href="~/css/site.css" rel="stylesheet" /> {% endcomment %}
    <link rel="icon" type="image/png" href="{% static 'assets/images/favicon.ico' %}">
</head>
<body>
  <header id="header" class="header header-classic" dir="rtl">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <!-- logo-->
            <a class="navbar-brand" href="{% url 'calendarapp:calendars'  %}">
                <img src="{% static 'assets/images/logos/logo-v3.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><i class="icon icon-menu"></i></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="ts-scroll" href="#Main">الرئيسية</a>
                    </li>
                    <li class="nav-item">
                        <a class="ts-scroll" href="#AboutUs">عن الملتقى</a>
                    </li>


                    <li class="nav-item">
                        <a class="ts-scroll" href="#Contact">للتواصل</a>
                    </li>

                   

                    {% comment %} <li class="header-ticket nav-item">
                        <a href="#popup_DeptRegister" class="ticket-btn btn ts-image-popup" data-effect="mfp-zoom-in">
                            تسجيل الجهات
                        </a>
                    </li> {% endcomment %}

                    {% if user.is_authenticated %}
                    <li class="header-ticket nav-item">
                      <a class="ticket-btn btn ts-image-popup" href="{% url 'calendarapp:calendar'  %}">({{ user.username }})</a>
                    </li>
                    <li class="header-ticket nav-item">
                      <a class="ticket-btn btn ts-image-popup" href="{% url 'accounts:signout' %}">Logout</a>
                    </li>
                      {% else %}
                        <a href="#popup_register" class="ticket-btn btn ts-image-popup" data-effect="mfp-zoom-in">
                          تسجيل الزوار
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    </div><!-- container end-->
</header>
<!-- <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
              {% comment %} <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Online Course</a> {% endcomment %}
              <a class="navbar-brand" href="{% url 'calendarapp:calendars' %}">All events</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn btn-link" href="#">({{ user.username }})</a>
                <a class="btn btn-link" href="{% url 'accounts:signout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <form class="form-inline" action="{% url 'accounts:signin' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                       
                        <button class="btn btn-primary" type="submit">Login</button>
                        <a class="btn btn-link" href="{% url 'accounts:signin' %}">Sign Up</a>
                    </div>
                </form>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>-->
<hr>
    {% comment %} {% block calendar %} {% endcomment %}

    {% comment %} {% endblock calendar %} {% endcomment %}
  {% block content %}

  {% endblock %}
  <br>
  <div class="footer-area">

    <!-- ts-book-seat start-->
    <hr>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="logo-box">
                    
                    <span>تنظيم الدورات بالتعاون مع</span>
                        <img src="{% static 'assets/images/logos/MFTC-logo.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div><!-- container end-->
    </section>
    <!-- book seat  end-->
    <!-- footer start-->
    <footer class="ts-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="ts-footer-social text-center mb-30">
                        <ul>
                            <li>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            <li>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>

                    <div class="copyright-text text-center">
                        <p>
                            جميع الحقوق محفوظة لوكالة عمادة شؤون الطلاب لشؤون الخريجين بالتعاون مع المركز الإداري والمالي للتدريب 
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer end-->
    <div class="BackTo">
        <a href="#" class="fa fa-angle-up" aria-hidden="true"></a>
    </div>
</div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>


    
  {% block script %}
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

website/templates/calendar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="clearfix">
    {% if request.user.is_staff %}
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_new' %}"> أضافة دورة جديدة </a>
    {% endif %}
</div>
<div class="container">
    <div>
        
        {{ calendar }}</table>
    </div>
</div>
<style>
    * {
      margin: 0;
      padding: 0;
    }
    body {
      direction: rtl;
    }
    nav.navbar.navbar-light.bg-light .container-fluid {
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    ul,
    ol {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    nav.navbar.navbar-light.bg-light {
      background: gray;
      padding: 15px;
    }

    a {
      text-decoration: none;
      color: inherit;
      text-transform: capitalize;
    }

    nav.navbar ul.nav.navbar-nav.navbar-right {
      display: flex;
      align-items: center;
      column-gap: 15px;
    }

    nav.navbar ul.nav.navbar-nav.navbar-right li a {
      background: #222;
      color: #fff;
      padding: 6px 12px;
      border-radius: 8px;
      font-size: 14px;
    }
    .table-content-araea {
      padding: 40px 0;
    }

    @media (min-width: 1101px) {
      .container {
        width: 1100px;
        margin: 0 auto;
      }
    }

    @media (max-width: 1100px) {
      .container {
        padding: 0 12px;
      }
      .table-tr a {
        display: inline-block;
      }
      .table-tr ul {
        width: 100%;
      }
    }

    .table-content-araea table.table.calendar {
      background: #cfcfcfcc;
      border: 1px solid #ccc;
      border-radius: 10px;
      empty-cells: hide;
      width: 100%;
    }

    tr.table-title th {
      background: #272955;
      padding: 10px;
      border: none;
      border-radius: 6px;
      color: #fff;
    }
    tr.table-tr th {
      background: #fff;
      padding: 20px 0;
      border: 1px solid #27295570;
      border-radius: 6px;
      color: #272955;
    }

    tr.table-tr td {
      background: #fff;
      padding: 20px 0;
      text-align: center;
      color: #000;
      border: 1px solid #27295570;
      border-radius: 6px;
    }

    .pages-links.clearfix {
      text-align: center;
      margin-top: 30px;
    }

    .pages-links.clearfix .btn {
      background: #272955;
      padding: 10px 20px;
      border-radius: 8px;
      color: #fff;
      margin: 0 5px;
    }
    .navbar-header {
      color: #fff;
      font-weight: bold;
    }
  </style>
  
{% endblock %}

website/templates/event-details.html
{% extends 'base.html' %}

{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      </div>
    {% endfor %}
</ul>
{% endif %}
        <div class="clearfix">
            
            {% if request.user.is_staff %}
            <a class="btn btn-primary left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
            <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_edit' event.pk %}"> Edit Event </a>
            {% endif %}
        </div>

        <div class="clearfix">
            <h3>اسم الدورة : {{ event.title }}</h3>
            <p><span style="color: gray;">{{ event.start_time }} من </span><br> <span style="color: gray;">{{ event.end_time }} الي </span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            {% if request.user.is_staff %}
            <h4 class="left" > Members of this Event</h4>
            <a class="btn btn-success right" href="{% url 'calendarapp:add_eventmember' event.id %}"> أضافة عضو يدويا </a>
            {% else %}
            <a class="btn btn-success right" href="{% url 'calendarapp:member_join' event.id %}"> التسجيل في هذة الدورة </a>
            <a class="btn btn-success left" href="{% url 'calendarapp:calendar' %}"> الأشتراك في دورة أخرى</a>
            {% endif %}
        </div>
        {% if request.user.is_staff %}
        <table class="table table-bordered">
            <thead>
                <tr>
                  <th style="width: 10px">#</th>
                  
                  <th>Username</th>
                  <th>Email</th>
                  {% if request.user.is_staff %}
                  <th>Action</th>
                    {% endif %}
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email }}</td>
                    {% if request.user.is_staff %}
                    <td>
                        <a class="btn btn-danger" href="{% url 'calendarapp:remove_event' member.id %}">Remove</a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
              </tbody>
        </table>
        {% endif %}
    </div>
{% endblock %}

website/templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
{% if request.user.is_staff %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

website/templates/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    {% if request.user.is_staff %}
        <form action="{% url 'calendarapp:delete_event'  %}" method="post">
            {% csrf_token %}
            
            <p>Are you sure you want to delete this event?{{event}}</p>
            <input type="submit" value="Delete">
        </form>
    {% else %}
        <p>You do not have permission to delete this event.</p>
    {% endif %}
{% endblock content %}

website/templates/qr_code.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if request.user.is_staff %}
    {% if messages %}
    <ul class="messages" style='text-align:center; list-style-type: none;'>
        {% for message in messages %}
        <div class="alert alert-info role="alert">
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          </div>
        
        {% endfor %}
    </ul>
    {% endif %}
{% endif %}
<div class="container" style='text-align:center;'>
    
    <div class="alert alert-dark" role="alert">
    <h1>{{qr}} التذكرة الخاصة بك</h1>
</div>

    <h2>شكرا لتسجيلك معنا</h2>
    {% comment %} <span id='qr'>
        {{qr.qr_code|safe}}
    </span> {% endcomment %}
    <img src="{{qr.image.url}}" alt="">
    <h5>{{qr.event}}</h5>
</div>

{% endblock %}